stages:
  prepare_data:
    wdir: ./
    cmd: python scripts/prepare_data.py
    deps:
      - ./scripts/prepare_data.py
      - ./nomelt/deduplication.py
      - ./data/database.ddb
    params:
      - data.min_temp_diff
      - data.min_thermo_temp
      - data.min_align_cov
      - data.kgram
      - data.minhash_threshold
      - data.minhash_num_perm
      - data.keep_only_extremes
      - data.test_size
      - data.dev_sample_data
    outs:
      - ./data/dataset/
    metrics:
      - ./data/data_metrics.yaml:
          cache: false
  train:
    wdir: ./
    cmd: accelerate launch --config_file ./.config/accelerate/default_config.yaml scripts/train.py 
    deps:
      - ./scripts/train.py
      - ./data/dataset/
      - ./.config/accelerate/default_config.yaml
    params:
      - model.pretrained_model
      - model.task
      - model.generation_max_length
      - model.model_hyperparams
      - training.keep_only_extremes
      - training.dev_sample_data
      - training.per_device_batch_size
      - training.gradient_accumulation
      - training.auto_find_batch_size
      - training.saves_per_epoch
      - training.epochs
      - training.gradient_checkpointing
      - training.learning_rate
      - training.lr_scheduler_type
      - training.label_smoothing_factor
      - training.warmup_ratio
      - training.optim
      - training.optim_args
      - training.max_eval_examples
      - training.fp16
      - training.bf16
      - training.early_stopping
      - training.early_stopping_patience
      - training.early_stopping_threshold
    outs:
      - ./data/nomelt-model/model/:
          persist: true
      - ./data/nomelt-model/live/report.md:
          cache: false
    metrics:
      - ./data/nomelt-model/live/metrics.json:
          cache: false
      - ./data/nomelt-model/live/plots/:
          cache: false
          persist: true
    plots:
      - ./data/nomelt-model/live/static/:
          cache: false
  score_model:
    wdir: ./
    cmd: python scripts/score_model.py
    deps:
      - ./scripts/score_model.py
      - ./data/nomelt-model/model/
      - ./data/dataset/
    params:
      - model.generation_max_length
      - model.generation_num_beams
    outs:
      - ./data/nomelt-model/test_metrics.yaml:
          cache: false


