stages:
  prepare_data:
    wdir: ./
    cmd: python scripts/prepare_data.py
    deps:
      - ./scripts/prepare_data.py
      - ./nomelt/deduplication.py
      - ./data/database.ddb
    params:
      - data.min_temp_diff
      - data.min_thermo_temp
      - data.min_align_cov
      - data.kgram
      - data.minhash_threshold
      - data.minhash_num_perm
      - data.keep_only_extremes
      - data.test_size
      - data.dev_sample_data
    outs:
      - ./data/dataset/
    metrics:
      - ./data/data_metrics.yaml:
          cache: false
  train:
    wdir: ./
    cmd: python scripts/train.py
    deps:
      - ./scripts/train.py
      - ./data/dataset/
    params:
      - training.keep_only_extremes
      - training.dev_sample_data
      - training.max_length
      - training.per_device_batch_size
      - training.gradient_accumulation
      - training.auto_find_batch_size
      - training.saves_per_epoch
      - training.epochs
      - training.gradient_checkpointing
      - training.learning_rate
      - training.lr_scheduler_type
      - training.label_smoothing_factor
      - training.warmup_ratio
      - training.optim
      - training.optim_args
      - training.max_eval_examples
      - training.fp16
      - model.pretrained_model
      - model.task
      - model.model_hyperparams
    outs:
      - ./data/nomelt-model/model/:
          persist: true
      - ./data/nomelt-model/live/report.md:
          cache: false
    metrics:
      - ./data/nomelt-model/live/metrics.json:
          cache: false
    plots:
      - ./data/nomelt-model/live/static/:
          cache: false

