stages:
  prepare_data:
    cmd: python prepare_data.py
    deps:
      - ./scripts/prepare_data.py
      - ./nomelt/deduplication.py
      - ./data/database.ddb
    params:
      - data.min_temp_diff
      - data.kgram
      - data.minhash_threshold
    outs:
      - ./data/dataset/
