name: nomelt
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - dvc
  - filelock=3.8.0
  - matplotlib=3.6.0
  - pandas=1.5.0
  - python=3.10.6
  - pyyaml=6.0
  - scikit-learn
  - tensorflow=2.11.0
  - pytorch
  - pytorch-cuda=11.7
  - transformers=4.26.0
  - evaluate
  - datasets
  - pip
  - pip:
    - duckdb==0.7.1
    - codecarbon==2.1.4
    - dvclive==2.1.0
    - datasketch
    - dpu_utils
    - nltk
    - git-lfs

