name: nomelt
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - dvc
  - dask
  - dask-jobqueue
  - filelock=3.8.0
  - matplotlib=3.6.0
  - pandas=1.5.0
  - python=3.9
  - pyyaml=6.0
  - scikit-learn
  - tensorflow
  - pytorch
  - pytorch-cuda=11.7
  - pytorch-lightning=1.9
  - cudatoolkit-dev
  - evaluate
  - datasets
  - clustalw
  - mdanalysis
  - pip
  - pip:
    - duckdb==0.7.1
    - codecarbon==2.1.4
    - dvclive==2.12.1
    - biopython
    - datasketch
    - accelerate
    - dpu_utils
    - nltk
    - git-lfs
    - sacrebleu
    - rouge_score
    - fair-esm @ git+https://github.com/facebookresearch/esm.git
    - deepspeed==0.10.0
    - transformers @ git+https://github.com/huggingface/transformers.git
    - dllogger @ git+https://github.com/NVIDIA/dllogger.git
    - openfold @ git+https://github.com/EvanKomp/openfold.git
    - modelcif
    - optuna
    - pillow

