data:
  min_thermo_temp: 65.0
  min_temp_diff: 35.0
  min_align_cov: 0.95
  kgram: 4
  minhash_threshold: 0.2
  minhash_num_perm: 128
  keep_only_extremes: false
  test_size: 0.1
  dev_sample_data: false
model:
  pretrained_model: "Rostlab/prot_t5_xl_uniref50"
  model_hyperparams:
    dropout_rate: 0.1
  task: 'translation' # one of 'reconstruction', 'translation'
training:
  keep_only_extremes: false # equivalent to data.keep_only_extremes, except the filtering happens before train time instead of in creating the saved dataset
  max_length: 250
  epochs: 5
  per_device_batch_size: 6
  auto_find_batch_size: true
  learning_rate: 1e-4
  gradient_accumulation: 24
  gradient_checkpointing: true
  saves_per_epoch: 5 # null means save only at the end of training
  lr_scheduler_type: 'linear'
  warmup_ratio: 0.1
  label_smoothing_factor: 0.0
  optim: "adafactor"
  optim_args: "scale_parameter=False,relative_step=False"
  fp16: true
  max_eval_examples: 1000
  dev_sample_data: 500

